/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.announcify;

public final class R {
    public static final class array {
        public static final int preference_list_reading_announcement_ids=0x7f080006;
        public static final int preference_list_reading_announcement_names=0x7f080003;
        public static final int preference_list_reading_break_ids=0x7f080009;
        public static final int preference_list_reading_break_names=0x7f080000;
        public static final int preference_list_reading_discreet_ids=0x7f080008;
        public static final int preference_list_reading_discreet_names=0x7f080005;
        public static final int preference_list_reading_mode_ids=0x7f08000f;
        public static final int preference_list_reading_mode_names=0x7f08000d;
        public static final int preference_list_reading_repeat_ids=0x7f08000a;
        public static final int preference_list_reading_repeat_names=0x7f080001;
        public static final int preference_list_reading_unknown_ids=0x7f080007;
        public static final int preference_list_reading_unknown_names=0x7f080004;
        public static final int preference_list_reading_wait_ids=0x7f08000b;
        public static final int preference_list_reading_wait_names=0x7f080002;
        public static final int preference_list_stream_ids=0x7f08000e;
        public static final int preference_list_stream_names=0x7f08000c;
    }
    public static final class attr {
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int bar_title=0x7f010000;
    }
    public static final class color {
        public static final int actionbar_background_end=0x7f050003;
        public static final int actionbar_background_item_pressed_end=0x7f050005;
        public static final int actionbar_background_item_pressed_start=0x7f050004;
        public static final int actionbar_background_start=0x7f050002;
        public static final int actionbar_separator=0x7f050000;
        public static final int actionbar_title=0x7f050001;
    }
    public static final class dimen {
        public static final int actionbar_height=0x7f060000;
        public static final int actionbar_item_height=0x7f060001;
        public static final int actionbar_item_width=0x7f060002;
    }
    public static final class drawable {
        public static final int action_bar_background=0x7f020000;
        public static final int action_bar_divider=0x7f020001;
        public static final int actionbar_background=0x7f020002;
        public static final int actionbar_btn=0x7f020003;
        public static final int actionbar_btn_normal=0x7f020004;
        public static final int actionbar_btn_pressed=0x7f020005;
        public static final int btn_check_buttonless_off=0x7f020006;
        public static final int btn_check_buttonless_on=0x7f020007;
        public static final int gd_action_bar_add_normal=0x7f020008;
        public static final int gd_action_bar_compose_normal=0x7f020009;
        public static final int gd_action_bar_edit_normal=0x7f02000a;
        public static final int gd_action_bar_export_normal=0x7f02000b;
        public static final int gd_action_bar_refresh_normal=0x7f02000c;
        public static final int gd_action_bar_share_normal=0x7f02000d;
        public static final int gd_action_bar_sort_by_size_normal=0x7f02000e;
        public static final int gd_action_bar_star_normal=0x7f02000f;
        public static final int gd_action_bar_talk_normal=0x7f020010;
        public static final int gd_segment_divider=0x7f020011;
        public static final int launcher_icon=0x7f020012;
        public static final int list_vertical_divider=0x7f020013;
        public static final int notification_icon=0x7f020014;
    }
    public static final class id {
        public static final int actionbar=0x7f0b0008;
        public static final int actionbar_actions=0x7f0b0005;
        public static final int actionbar_home=0x7f0b0001;
        public static final int actionbar_home_bg=0x7f0b0003;
        public static final int actionbar_home_btn=0x7f0b0004;
        public static final int actionbar_home_logo=0x7f0b0002;
        public static final int actionbar_item=0x7f0b0007;
        public static final int actionbar_title=0x7f0b0006;
        public static final int auto_edit_chooser=0x7f0b000a;
        public static final int button_add=0x7f0b001a;
        public static final int button_address=0x7f0b0012;
        public static final int button_address_type=0x7f0b0013;
        public static final int button_event=0x7f0b0014;
        public static final int button_firstname=0x7f0b000d;
        public static final int button_fullname=0x7f0b0010;
        public static final int button_lastname=0x7f0b000e;
        public static final int button_message=0x7f0b0015;
        public static final int button_name=0x7f0b000c;
        public static final int button_nickname=0x7f0b000f;
        public static final int button_speak=0x7f0b0019;
        public static final int button_title=0x7f0b0011;
        public static final int check=0x7f0b001f;
        public static final int check_block_groups=0x7f0b0009;
        public static final int edit_formatstring=0x7f0b000b;
        public static final int edit_replace=0x7f0b0017;
        public static final int edit_with=0x7f0b0018;
        public static final int icon=0x7f0b001d;
        public static final int menu_about=0x7f0b002b;
        public static final int menu_activate=0x7f0b0023;
        public static final int menu_edit=0x7f0b0025;
        public static final int menu_help=0x7f0b0027;
        public static final int menu_plugins=0x7f0b0028;
        public static final int menu_rate=0x7f0b0029;
        public static final int menu_remove=0x7f0b0021;
        public static final int menu_report=0x7f0b0024;
        public static final int menu_share=0x7f0b002a;
        public static final int menu_toggle=0x7f0b0026;
        public static final int menu_uninstall=0x7f0b0022;
        public static final int plugin=0x7f0b001e;
        public static final int screen=0x7f0b0000;
        public static final int section=0x7f0b001c;
        public static final int textLeft=0x7f0b001b;
        public static final int web_help=0x7f0b0016;
        public static final int widget_control_button=0x7f0b0020;
    }
    public static final class layout {
        public static final int actionbar=0x7f030000;
        public static final int actionbar_item=0x7f030001;
        public static final int actionbar_list=0x7f030002;
        public static final int activity_choose=0x7f030003;
        public static final int activity_formatstring=0x7f030004;
        public static final int activity_help=0x7f030005;
        public static final int activity_replace=0x7f030006;
        public static final int list_header=0x7f030007;
        public static final int list_item_choose=0x7f030008;
        public static final int list_item_plugin=0x7f030009;
        public static final int widget_control=0x7f03000a;
    }
    public static final class menu {
        public static final int context_choose=0x7f0a0000;
        public static final int context_main=0x7f0a0001;
        public static final int context_replace=0x7f0a0002;
        public static final int menu_main=0x7f0a0003;
    }
    public static final class string {
        public static final int allow=0x7f07002f;
        public static final int app_name=0x7f07000e;
        public static final int application_error=0x7f070030;
        public static final int buy_button=0x7f070033;
        /**  License checking status messages 
         */
        public static final int check_license=0x7f07002c;
        public static final int checking_license=0x7f07002d;
        public static final int dont_allow=0x7f07002e;
        public static final int preference_behavior_title=0x7f070014;
        public static final int preference_break_summary=0x7f070003;
        public static final int preference_break_title=0x7f070002;
        public static final int preference_cache_summary=0x7f070029;
        public static final int preference_cache_title=0x7f070028;
        public static final int preference_choose_group_summary=0x7f070023;
        public static final int preference_choose_group_title=0x7f070022;
        public static final int preference_contact_title=0x7f07001d;
        public static final int preference_default_title=0x7f070024;
        public static final int preference_discreet_condition_summary=0x7f070018;
        public static final int preference_discreet_condition_title=0x7f070017;
        public static final int preference_discreet_summary=0x7f07000d;
        public static final int preference_discreet_title=0x7f07000c;
        public static final int preference_filter_group_summary=0x7f070021;
        public static final int preference_filter_group_title=0x7f070020;
        public static final int preference_general_title=0x7f070025;
        public static final int preference_gravity_condition_summary=0x7f07001a;
        public static final int preference_gravity_condition_title=0x7f070019;
        public static final int preference_known_summary=0x7f07000b;
        public static final int preference_known_title=0x7f07000a;
        public static final int preference_notification_summary=0x7f07001c;
        public static final int preference_notification_title=0x7f07001b;
        public static final int preference_reading_mode_summary=0x7f07001f;
        public static final int preference_reading_mode_title=0x7f07001e;
        public static final int preference_repeat_summary=0x7f070005;
        public static final int preference_repeat_title=0x7f070004;
        public static final int preference_ringtone_summary=0x7f070001;
        public static final int preference_ringtone_title=0x7f070000;
        public static final int preference_screen_condition_summary=0x7f070016;
        public static final int preference_screen_condition_title=0x7f070015;
        public static final int preference_spam_summary=0x7f07002b;
        public static final int preference_spam_title=0x7f07002a;
        public static final int preference_specific_title=0x7f07000f;
        public static final int preference_speech_title=0x7f070010;
        public static final int preference_stream_summary=0x7f070012;
        public static final int preference_stream_title=0x7f070011;
        public static final int preference_translate_summary=0x7f070027;
        public static final int preference_translate_title=0x7f070026;
        public static final int preference_tts_title=0x7f070013;
        public static final int preference_unknown_summary=0x7f070009;
        public static final int preference_unknown_title=0x7f070008;
        public static final int preference_wait_summary=0x7f070007;
        public static final int preference_wait_title=0x7f070006;
        public static final int quit_button=0x7f070034;
        public static final int unlicensed_dialog_body=0x7f070032;
        /**  Unlicensed dialog messages 
         */
        public static final int unlicensed_dialog_title=0x7f070031;
    }
    public static final class style {
        public static final int ActionBar=0x7f090000;
        public static final int ActionBarHomeItem=0x7f090002;
        public static final int ActionBarItem=0x7f090001;
        public static final int Theme_Light_NoTitleBar_Announcify=0x7f090003;
    }
    public static final class xml {
        public static final int preferences_main_settings=0x7f040000;
        public static final int preferences_settings=0x7f040001;
    }
    public static final class styleable {
        /** Attributes that can be used with a ActionBar.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ActionBar_bar_title com.announcify:bar_title}</code></td><td></td></tr>
           </table>
           @see #ActionBar_bar_title
         */
        public static final int[] ActionBar = {
            0x7f010000
        };
        /**
          <p>This symbol is the offset where the {@link com.announcify.R.attr#bar_title}
          attribute's value can be found in the {@link #ActionBar} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:bar_title
        */
        public static final int ActionBar_bar_title = 0;
    };
}
